config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about', to: 'about#show'

  get '/info', to: 'info#show'

  get '/alerts', to: 'alerts#index'

  get '/twitter', to: 'twitter#show'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'

  get '/auth/google/callback', to: 'sessions#create'
  get '/auth/google', as: 'google_login'

  get '/auth/twitter/callback', to: 'sessions#create'
  get '/auth/twitter', as: 'twitter_login'

  get '/auth/facebook/callback', to: 'sessions#create'
  get '/auth/facebook', as: 'facebook_login'

  namespace :host_shelters do
    get '/sign_up', to: 'properties#new'
    resources :properties, only: [:create, :new, :index] do
      post "status_accepted", :action => :status_accepted
      post "status_cancelled", :action => :status_cancelled
      post "status_complete", :action => :status_complete
      resources :reservations, only: [:index]
    end
    get '/:id', to: 'properties#show'
  end

  resources :users, only: [:new, :create] do
    resources :properties, only: [:index]
  end

  resources :contact_forms, only: [:new, :create]

end

app/models/alert.rb
class Alert
  attr_reader :event, :headline, :description,
              :instructions, :severity, :urgency

  def initialize(alert_info)
    @event        = alert_info[:event]
    @headline     = alert_info[:headline]
    @description  = alert_info[:description]
    @instructions = alert_info[:instruction]
    @severity     = alert_info[:severity]
    @urgency      = alert_info[:urgency]
  end

  def self.find_all
    api_alerts = WeatherAlertService.find_national_alerts
    api_alerts.map do |api_alert|
      new(api_alert[:properties])
    end
  end

  def self.find_by(state)
    api_alerts = WeatherAlertService.find_alerts_for(state)
    api_alerts.map do |api_alert|
      new(api_alert[:properties])
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,     validates: true
  attribute :email,    validates: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  def headers
    {
      to: 'homesshelter@gmail.com',
      from: %("#{name}" <#{email}>)
    }
  end

  def self.send_message(content)
    new(name: content[:name], email: content[:email], message: content[:message]).deliver
  end
end

app/models/direction.rb
class Direction
  attr_reader :steps, :duration, :distance, :start_address, :end_address

  def initialize(directions)
    @steps         = re_format(directions[:steps])
    @duration      = directions[:duration][:text]
    @distance      = directions[:distance][:text]
    @start_address = directions[:start_address]
    @end_address   = directions[:end_address]
  end

  def self.take_me_to(location, destination)
    new_location = address_formatter(location)
    new_destination = address_formatter(destination)
    new(DirectionService.find_directions(new_location, new_destination))
  end

  def re_format(steps)
    steps.map do |attr|
      DirectionStep.new(attr)
    end
  end

  def self.address_formatter(address)
    address.delete(",").gsub!(" ", "+")
  end
end

app/models/direction_step.rb
class DirectionStep
  attr_reader :html_instructions, :approx_distance, :approx_duration

  def initialize(step_hash)
    @html_instructions = step_hash[:html_instructions]
    @approx_duration   = step_hash[:duration][:text]
    @approx_distance   = step_hash[:distance][:text]
  end
end

app/models/property.rb
class Property < ApplicationRecord
  before_save :address
  before_save :latitude_look_up
  before_save :longitude_look_up

  belongs_to :user

  has_many :reservations

  def address
    self.address = "#{street_address}, #{city}, #{state}"
  end

  def longitude_look_up
    self.longitude = Geocoder.coordinates(self.address).last
  end

  def latitude_look_up
    self.latitude = Geocoder.coordinates(self.address).first
  end

  def coordinates
    [self.latitude, self.longitude]
  end

  def self.all_coordinates
    all.map {|property| property = [property.latitude, property.longitude]}
  end

  def self.search(location)
    location = location[:search]
    where("street_address ILIKE ? OR city ILIKE ? OR state ILIKE ?", "%#{location}%", "%#{location}%", "%#{location}%")
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :property
  belongs_to :user

  enum status: %w(pending approved completed cancelled)
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/user.rb
class User < ApplicationRecord
  before_save :user_role_create

  has_many :authorizations

  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :properties

  has_many :reservations

  has_secure_password
  validates_confirmation_of :password
  validates :password, :presence => true, :confirmation => true
  validates :email, :presence => true, :uniqueness => true
  # validates :first_name, presence: true
  # validates :last_name, presence: true
  #validates :email, presence: true, uniqueness: true


  def self.from_omniauth(auth)
    user = find_or_create_by(uid: auth[:uid]) do |user|
      user.uid        = auth["uid"]
      user.first_name = auth["info"]["first_name"]
      user.last_name  = auth["info"]["last_name"]
      user.email      = auth["info"]["email"]
      user.image      = auth["info"]["image"]
      user.token      = auth["credentials"]["token"]
      user.password   = "password"
    end
  end

  def self.create_from_hash!(hash)
    create(first_name: hash[:extra][:raw_info][:name],
           email:      hash[:extra][:raw_info][:email],
           uid:        hash[:extra][:raw_info][:id],
           token:      hash[:credentials][:token])
           
    # user = find_or_create_by(uid: auth[:uid]) do |user|
    #   user.uid        = hash[:extra][:raw_info][:id]
    #   user.first_name = hash[:extra][:raw_info][:name]
    #   user.email      = hash[:extra][:raw_info][:email]
    #   user.token      = hash[:credentials][:token]
    # end
  end

  def user?
    roles.exists?(name: "user")
  end

  def owner!
    self.roles << Role.find_by(name: "owner")
  end

  def owner?
    roles.exists?(name: "owner")
  end

  private

  def user_role_create
    self.roles << Role.find_by(name: "user")
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  def index
    state = params[:state]
    state ? @alerts = Alert.find_by(state) : @alerts = Alert.find_all
    @st = params[:state]
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.create(safe_params)
    if user.save
      session[:user_id] = user.id
      UserMailer.welcome_email(user).deliver_now
      redirect_to twitter_path
    else
      redirect_to new_user_path
    end
  end

  private

  def safe_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  endd
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @properties = all_properties
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def map_or_login_tiles_toggle
    if current_user
      concat(render(:partial => 'welcome/map'))
    else
      concat(render(:partial => 'welcome/login_tiles'))
    end
  end

end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login_tiles.html.erb
<h1>Welcome to Shelter, a community based app for those in need and those wanting to help.<br/>
  Please click one of the options below to log in.</h1>
 
  <section class="tiles">
    <article class="style1">
      <span class="image">
        <%= image_tag "g.png" %>
      </span>
      <a href="<%= google_login_path %>">
        <h2>Google</h2>
        <div class="content">
          <p>Use Google Authentication to sign in.</p>
        </div>
      </a>
    </article>

    <article class="style2">
      <span class="image">
        <%= link_to image_tag('fb.png'), "https://www.facebook.com/v2.10/dialog/oauth?client_id=#{ENV['FACEBOOK_APP_ID']}&redirect_uri=http://localhost:3000/users/new&scope=email,public_profile" %>
      </span>
        <div class="content">
        </div>
      </a>
    </article>

    <article class="style3">
      <span class="image">
        <%= image_tag "typing.png" %>
      </span>
      <a href="<%= login_path %>">
        <h2>Manual</h2>
        <div class="content">
          <p>Sign in manually to access the app.</p>
        </div>
      </a>
    </article>
  </section>

app/views/welcome/_map.html.erb
<!-- JIMMY, this needs a responsive wrapper -->

  <% if current_user %>
    <strong><h2 style="color:red;"> <%= link_to "Can you help those in need? Click here to sign up to be a host.", host_shelters_sign_up_path %> </h2></strong>
  <% end %>

  <h2>Check the map below if you are seeking shelter.</h2>

  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

app/views/welcome/_search.html.erb
  <%= form_tag :alerts, method: :get, class: "form-inline" do %>
      <%= text_field_tag :state, "Enter a State abbreviation here to see Weather...", class: "form-control" %>
      <br>
      <%= submit_tag "Search" %>
  <% end %>

app/views/welcome/index.html.erb
<%= content_tag("div", nil, :id => 'js-properties', :data => {:properties => all_coordinates}) %>
<%= javascript_include_tag 'map.js', type: "text/javascript"%>
<script src="//maps.google.com/maps/api/js?key=<%= ENV["API_KEY"] %>"></script>
<script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["API_KEY"] %>&callback=initMap"
type="text/javascript">
</script>

<h1>Welcome to Shelter, a community based app for those in need and those wanting to help.<br />
Please click one of the options below to log in.</h1>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<section class="tiles">
  <article class="style1">
    <span class="image">
      <%= image_tag "g.png" %>
    </span>
    <a href="<%= google_login_path %>">
      <h2>Google</h2>
      <div class="content">
        <p>Use Google Authentication to sign in.</p>
      </div>
    </a>
  </article>
  <article class="style2">
    <span class="image">
      <%= image_tag "fb.png" %>
    </span>
    <a href="fb.html">
      <h2>Facebook</h2>
      <div class="content">
        <p>Use Facebook Authentication to sign in.</p>
      </div>
    </a>
  </article>
  <article class="style3">
    <span class="image">
      <%= image_tag "typing.png" %>
    </span>
    <a href="<%= login_path %>">
      <h2>Manual</h2>
      <div class="content">
        <p>Sign in manually to access the app.</p>
      </div>
    </a>
  </article>
</section>

<%= link_to "View Weather Alerts", alerts_path %>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav">
    <%= form_tag :alerts, method: :get, class: "form-inline" do %>
      <div class="form-group search-field">
        <%= text_field_tag :state, "Search by State...", class: "form-control" %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </ul>
</div>


<%= button_to "About", about_path, method: :get, class: "about-btn" %>
<%= button_to "How It Works", info_path, method: :get, class: "info-btn" %>
<% if current_user %>
  <p>Welcome, <%= current_user.first_name %></p>
  <%= link_to "Logout", logout_path, method: :delete , class: "logout-button"%>
<% end %>